### ISSUE TITLE
Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/tf_model.h5

### ISSUE THREAD

**Issue by luoshuiyang** [text2cinemagraph/text2cinemagraph#10]
Hello, because I can't load the model on huggingface online, I need to change the place where clip-vit-large-patch14 is loaded online in the code to load it locally; but I can't find the modified location. Can you help point out this model loading? Well, I'm looking forward to your reply.

**Comment by anime26398** [comment]
Hi! I dont understand your question exactly. Can you please also share the error log? Thanks.

**Comment by luoshuiyang** [comment]
![image](https://github.com/text2cinemagraph/text2cinemagraph/assets/83381239/57551e0e-cb83-4451-9012-9396e0b5eb7f)
@anime26398

**Comment by anime26398** [comment]
From the error log, when i tried to check https://huggingface.co/CompVis/stable-diffusion-v1-3-original, it gives 404 error (page does not exist). Is there any specific reason why you want to try sd-v1-3-original. Can you instead use sd-v1-4. Also, let me know if the error occurs in ODISE part. The code for ODISE was taken from [https://github.com/NVlabs/ODISE](https://github.com/NVlabs/ODISE). Can you please check this repo made some changes with the stable-diffusion model they were using. Thanks!

**Comment by heir0412** [comment]
I encountered the same problem. Which code should I modify? I didn't find it.
