### ISSUE TITLE
How to determine ODISE vocab?

### ISSUE THREAD

**Issue by JC1DA** [text2cinemagraph/text2cinemagraph#8]
Hi, thanks a lot for your great works.

I'm wondering if we want to generate for different scene, do we need to change ODISE vocab? If so, how can we choose a good set of words?

**Comment by anime26398** [comment]
The ODISE vocab describes what objects will be inside the mask (as in objects that will be animatable in the final video). For example, if you want to animate river, the ODISE vocab should contain "river". If you want to animate an object that is not in the current vocab, you can change the vocab by adding the word (and probably removing some from the vocab if you dont want to animate those regions). Please let me know if this explains your question.
